# Generated by Django 4.1.6 on 2023-02-16 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anggota', '0003_remove_anggota_nama_orang_tua_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jam_absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default='00:00:00')),
                ('end', models.TimeField(default='00:00:00')),
                ('deskripsi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_absen', models.TimeField(editable=False)),
                ('tgl_absem', models.DateField()),
                ('anggota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='anggota.anggota')),
                ('jam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='absen.jam_absen')),
            ],
        ),
    ]
