# Generated by Django 4.1.6 on 2023-02-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam_absen', models.TimeField(editable=False)),
                ('tgl_absem', models.DateField()),
            ],
        ),
    ]
