# Generated by Django 4.1.6 on 2023-02-16 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absen',
            old_name='tgl_absem',
            new_name='tgl_absen',
        ),
    ]
