# Generated by Django 4.1.6 on 2023-02-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0003_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
