# Generated by Django 4.1.6 on 2023-02-16 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_anggota_nama_orang_tua_anggota_no_orang_tua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anggota',
            name='nama_orang_tua',
        ),
        migrations.RemoveField(
            model_name='anggota',
            name='no_orang_tua',
        ),
    ]
