# Generated by Django 4.1.6 on 2023-02-16 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0003_remove_anggota_nama_orang_tua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anggota',
            name='nama_orang_tua',
            field=models.CharField(default='kosong', max_length=100),
        ),
        migrations.AddField(
            model_name='anggota',
            name='no_telp_orang_tua',
            field=models.CharField(default='kosong', max_length=100),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='nama',
            field=models.CharField(default='kosong', max_length=100),
        ),
        migrations.AlterField(
            model_name='anggota',
            name='slug',
            field=models.CharField(default='kosong', max_length=100),
        ),
    ]
